//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applenium.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Applenium.Properties.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.BatchLogic.
        /// </summary>
        internal static string Query_BatchScenariosToSelenium {
            get {
                return ResourceManager.GetString("Query_BatchScenariosToSelenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from QA_Autotest.INFORMATION_SCHEMA.COLUMNS.
        /// </summary>
        internal static string Query_Columns {
            get {
                return ResourceManager.GetString("Query_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE QA_Autotest.Test.GuiMap WHERE GuiMapObjectName= .
        /// </summary>
        internal static string Query_Delete_GuiMap {
            get {
                return ResourceManager.GetString("Query_Delete_GuiMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.BatchLogic.
        /// </summary>
        internal static string Query_GuiBatchLogicSelect {
            get {
                return ResourceManager.GetString("Query_GuiBatchLogicSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.Batches.
        /// </summary>
        internal static string Query_GuiBatchSelect {
            get {
                return ResourceManager.GetString("Query_GuiBatchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiMap.
        /// </summary>
        internal static string Query_GuiMapSelect {
            get {
                return ResourceManager.GetString("Query_GuiMapSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiProjectPage.
        /// </summary>
        internal static string Query_GuiProjectsSelect {
            get {
                return ResourceManager.GetString("Query_GuiProjectsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiScenarioLogic.
        /// </summary>
        internal static string Query_GuiScenarioLogicSelect {
            get {
                return ResourceManager.GetString("Query_GuiScenarioLogicSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.Scenario.
        /// </summary>
        internal static string Query_GuiScenarioSelect {
            get {
                return ResourceManager.GetString("Query_GuiScenarioSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TestName FROM QA_Autotest.Test.Test.
        /// </summary>
        internal static string Query_GuiTestSelect {
            get {
                return ResourceManager.GetString("Query_GuiTestSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiTestSteps.
        /// </summary>
        internal static string Query_GuiTestStepsSelect {
            get {
                return ResourceManager.GetString("Query_GuiTestStepsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select InputTableName From QA_Autotest.Test.Test.
        /// </summary>
        internal static string Query_InputTableNameSelect {
            get {
                return ResourceManager.GetString("Query_InputTableNameSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rowID from .
        /// </summary>
        internal static string Query_RowsID {
            get {
                return ResourceManager.GetString("Query_RowsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiScenarioLogic.
        /// </summary>
        internal static string Query_ScenarioTestsToSelenium {
            get {
                return ResourceManager.GetString("Query_ScenarioTestsToSelenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.sys.tables.
        /// </summary>
        internal static string Query_Tables {
            get {
                return ResourceManager.GetString("Query_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiTagType.
        /// </summary>
        internal static string Query_TagTypeSelect {
            get {
                return ResourceManager.GetString("Query_TagTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM QA_Autotest.Test.GuiTestSteps.
        /// </summary>
        internal static string Query_TestStepsToSlenium {
            get {
                return ResourceManager.GetString("Query_TestStepsToSlenium", resourceCulture);
            }
        }
    }
}
