/*
Deployment script for QA_Autotest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "QA_Autotest"
:setvar DefaultFilePrefix "QA_Autotest"
:setvar DefaultDataPath "C:\Users\maximgu\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\maximgu\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [Test]...';


GO
CREATE SCHEMA [Test]
    AUTHORIZATION [dbo];



GO
PRINT N'Creating [Test].[Test]...';


GO
CREATE TABLE [Test].[Test] (
    [TestId]               INT            IDENTITY (1, 1) NOT NULL,
    [TestName]             NVARCHAR (50)  NOT NULL,
    [ProjectID]            INT            NULL,
    [InputTableName]       NVARCHAR (50)  NULL,
    [IsAPI]                INT            NULL,
    [Description]          NVARCHAR (MAX) NULL,
    [StatusCompletedImage] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED ([TestId] ASC) 
);


GO
PRINT N'Creating [Test].[Scenario]...';


GO
CREATE TABLE [Test].[Scenario] (
    [ScenarioID]   INT            IDENTITY (1, 1) NOT NULL,
    [ScenarioName] NVARCHAR (MAX) NOT NULL,
    [IsAPI]        INT            NULL,
    [Description]  NVARCHAR (MAX) NULL,
    [ProjectID]    INT            NULL,
    CONSTRAINT [PK_Flow] PRIMARY KEY CLUSTERED ([ScenarioID] ASC) 
);


GO
PRINT N'Creating [Test].[GuiMap]...';


GO
CREATE TABLE [Test].[GuiMap] (
    [GuiMapID]         INT            IDENTITY (1, 1) NOT NULL,
    [GuiMapObjectName] NVARCHAR (MAX) NOT NULL,
    [TagTypeID]        INT            NOT NULL,
    [TagTypeValue]     NVARCHAR (MAX) NOT NULL,
    [GuiProjectID]     INT            NOT NULL,
    CONSTRAINT [PK_GuiMapObject1] PRIMARY KEY CLUSTERED ([GuiMapID] ASC) 
);


GO
PRINT N'Creating [Test].[GuiTestSteps]...';


GO
CREATE TABLE [Test].[GuiTestSteps] (
    [GuiTestStepsID]  INT            IDENTITY (1, 1) NOT NULL,
    [GuiTestID]       INT            NOT NULL,
    [GuiMapID]        INT            NOT NULL,
    [GuiMapCommandID] INT            NOT NULL,
    [InputDataColumn] NVARCHAR (50)  NULL,
    [IsValidate]      INT            NULL,
    [InputDataRow]    NVARCHAR (MAX) NULL,
    [StepsOrder]      INT            NOT NULL,
    CONSTRAINT [PK_GuiTestSteps1] PRIMARY KEY CLUSTERED ([GuiTestStepsID] ASC) 
);


GO
PRINT N'Creating [Test].[BatchLogic]...';


GO
CREATE TABLE [Test].[BatchLogic] (
    [BatchLogicID]      INT IDENTITY (1, 1) NOT NULL,
    [BatchID]           INT NOT NULL,
    [ScenarioID]        INT NOT NULL,
    [BrowserID]         INT NULL,
    [ExecutionStatusID] INT NULL
);


GO
PRINT N'Creating [Test].[BatchLogic].[BatchLogicID]...';


GO
CREATE CLUSTERED INDEX [BatchLogicID]
    ON [Test].[BatchLogic]([BatchLogicID] ASC) ;


GO
PRINT N'Creating [Test].[Batches]...';


GO
CREATE TABLE [Test].[Batches] (
    [BatchID]   INT           IDENTITY (1, 1) NOT NULL,
    [BatchName] NVARCHAR (50) NOT NULL,
    [ProjectID] INT           NULL
);


GO
PRINT N'Creating [Test].[Batches].[BatchID]...';


GO
CREATE CLUSTERED INDEX [BatchID]
    ON [Test].[Batches]([BatchID] ASC) ;


GO
PRINT N'Creating [Test].[GuiProjectPage]...';


GO
CREATE TABLE [Test].[GuiProjectPage] (
    [GuiProjectPageID] INT            IDENTITY (1, 1) NOT NULL,
    [ProjectID]        INT            NOT NULL,
    [ProjectPageName]  NVARCHAR (MAX) NOT NULL,
    [PageURL]          NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_GuiProject_1] PRIMARY KEY CLUSTERED ([GuiProjectPageID] ASC) 
);


GO
PRINT N'Creating [Test].[Browsers]...';


GO
CREATE TABLE [Test].[Browsers] (
    [BrowserID]   INT            IDENTITY (1, 1) NOT NULL,
    [BrowserName] NVARCHAR (MAX) NOT NULL
);


GO
PRINT N'Creating [Test].[Browsers].[BrowserID]...';


GO
CREATE CLUSTERED INDEX [BrowserID]
    ON [Test].[Browsers]([BrowserID] ASC) ;


GO
PRINT N'Creating [Test].[TestResults]...';


GO
CREATE TABLE [Test].[TestResults] (
    [ResultsIndex]   INT            IDENTITY (1, 1) NOT NULL,
    [RunExecutionID] INT            NOT NULL,
    [BatchID]        INT            NOT NULL,
    [ScenarioID]     INT            NOT NULL,
    [TestID]         INT            NOT NULL,
    [StepID]         INT            NOT NULL,
    [Description]    NVARCHAR (MAX) NOT NULL,
    [Status]         INT            NOT NULL,
    [OutOfFlow]      NVARCHAR (50)  NOT NULL,
    [TimeStamp]      ROWVERSION     NOT NULL,
    [ProjectID]      INT            NOT NULL,
    [ProjectPageID]  INT            NOT NULL,
    [Occured]        DATETIME       NULL,
    [FailureLogID]   INT            NULL,
    [IsRelease]      TINYINT        NULL
);


GO
PRINT N'Creating [Test].[TestResults].[ResultsIndex]...';


GO
CREATE CLUSTERED INDEX [ResultsIndex]
    ON [Test].[TestResults]([ResultsIndex] ASC) ;


GO
PRINT N'Creating [Test].[LogStatus]...';


GO
CREATE TABLE [Test].[LogStatus] (
    [LogStatusID]          INT           IDENTITY (1, 1) NOT NULL,
    [LogStatusDescription] NVARCHAR (50) NOT NULL
);


GO
PRINT N'Creating [Test].[LogStatus].[LogStatusID]...';


GO
CREATE CLUSTERED INDEX [LogStatusID]
    ON [Test].[LogStatus]([LogStatusID] ASC) ;


GO
PRINT N'Creating [Test].[GuiPageSection]...';


GO
CREATE TABLE [Test].[GuiPageSection] (
    [GuiPageSectionID]   INT            IDENTITY (1, 1) NOT NULL,
    [GuiPageID]          INT            NOT NULL,
    [GuiPageSectionName] NVARCHAR (MAX) NOT NULL
);


GO
PRINT N'Creating [Test].[GuiPageSection].[GuiPageSectionID]...';


GO
CREATE CLUSTERED INDEX [GuiPageSectionID]
    ON [Test].[GuiPageSection]([GuiPageSectionID] ASC) ;


GO
PRINT N'Creating [Test].[GuiTagType]...';


GO
CREATE TABLE [Test].[GuiTagType] (
    [TagTypeID] INT        IDENTITY (1, 1) NOT NULL,
    [TagType]   NCHAR (50) NOT NULL,
    CONSTRAINT [PK_GUIObjectDefenitionType] PRIMARY KEY CLUSTERED ([TagTypeID] ASC) 
);


GO
PRINT N'Creating [Test].[Projects]...';


GO
CREATE TABLE [Test].[Projects] (
    [GuiProjectID]          INT           IDENTITY (1, 1) NOT NULL,
    [GuiProjectName]        NVARCHAR (50) NOT NULL,
    [GuiProjectDescription] NVARCHAR (50) NULL,
    [GuiProjectURL]         NVARCHAR (50) NULL,
    [Prefix]                NCHAR (10)    NULL,
    CONSTRAINT [PK_GuiProject] PRIMARY KEY CLUSTERED ([GuiProjectID] ASC) 
);


GO
PRINT N'Creating [Test].[EnvironmentVersion]...';


GO
CREATE TABLE [Test].[EnvironmentVersion] (
    [EnvironmentVersionId]   INT            IDENTITY (1, 1) NOT NULL,
    [EnvironmentVersionName] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_EnvironmentVersion] PRIMARY KEY CLUSTERED ([EnvironmentVersionId] ASC)
);


GO
PRINT N'Creating [Test].[GuiScenarioLogic]...';


GO
CREATE TABLE [Test].[GuiScenarioLogic] (
    [GuiScenarioLogicID] INT            IDENTITY (1, 1) NOT NULL,
    [GuiScenarioID]      INT            NOT NULL,
    [GuiTestID]          INT            NOT NULL,
    [InputDataRow]       NVARCHAR (MAX) NULL,
    [StepsOrder]         INT            NOT NULL,
    CONSTRAINT [PK_GuiScenarioLogic] PRIMARY KEY CLUSTERED ([GuiScenarioLogicID] ASC) 
);


GO
PRINT N'Creating [Test].[nums]...';


GO
CREATE TABLE [Test].[nums] (
    [id]  INT        NULL,
    [str] NCHAR (10) NULL
)
;


GO
PRINT N'Creating [Test].[TestCommand]...';


GO
CREATE TABLE [Test].[TestCommand] (
    [TestCommandID]   INT           IDENTITY (1, 1) NOT NULL,
    [TestCommandName] NVARCHAR (50) NOT NULL,
    [SeleniumCommand] NVARCHAR (50) NULL,
    CONSTRAINT [PK_TestCommand] PRIMARY KEY CLUSTERED ([TestCommandID] ASC) 
);



GO
PRINT N'Update complete.';


GO
